# Generated by Django 4.0.4 on 2022-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urlid',
            new_name='uuid',
        ),
    ]
